appname: "AtomBus"
charset: "UTF-8"

page_size: 100

plugins:
    DBIC:
        atombus:
            schema_class: "AtomBus::Schema"
            dsn: "dbi:mysql:database=atombus"
            user: root
